name: xrshell
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  xrshell:
    type: application
    platform: iOS
    sources:
      - path: Sources/xrshell
    settings:
      # 1. Point to your static file
      INFOPLIST_FILE: Info.plist
      
      # 2. CRITICAL: Tell Xcode to merge build settings into the plist
      GENERATE_INFOPLIST_FILE: YES
      
      # 3. Define the icon name here. Xcode will now inject this into the generated plist.
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      RECOMMENDED_ASSET_TYPES: "appicon"

      # Standard Settings
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0